markdown: rdiscount
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

host: echolihao.github.com

custom:
    category:
        thinking: 闭门思考
        problems: 问题记录
        knowledge: 知识经验
    categories:
      - name:  thinking
        title: 闭门思考

      - name:  problems
        title: 问题记录

      - name:  knowledge
        title: 知识经验

meta:
    authors:
      - name: echolihao
        email: bugbubble.lihao@gmail.com
        gravatar: 2bea517a9ae0dace8153745dd14ff469

    gravatar:
        base: http://www.gravatar.com/avatar/
        param: ?s=
